name: melon_mod
description: "Minecraft Fabric/Quilt mod manager for desktop."
publish_to: 'none'
version: 1.7.7+1
homepage: https://github.com/xyrusL/melon_mod_manager
repository: https://github.com/xyrusL/melon_mod_manager
issue_tracker: https://github.com/xyrusL/melon_mod_manager/issues

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  flutter_riverpod: ^3.3.1
  http: ^1.6.0
  file_picker: ^11.0.1
  path_provider: ^2.1.5
  path: ^1.9.0
  archive: ^4.0.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.5
  collection: ^1.18.0
  google_fonts: ^8.0.2
  crypto: ^3.0.5
  flutter_svg: ^2.2.4
  package_info_plus: ^9.0.1
  url_launcher: ^6.3.2
  window_manager: ^0.5.1
  desktop_drop: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
